application_name="Alfresco Proxy"
alfresco_health_endpoint="/alfresco/s/admin-spg/healthcheck"
spg_certificate_bucket = "tf-eu-west-2-hmpps-eng-dev-certificates-private-s3bucket"

pre_apply_stack_commands = "dummy-command.sh"
stack_post_build_commands = "afresco-proxy-stack-post-build-commands.sh"
stack_pre_build_environment = "export-alfresco-proxy-environment.sh"
target_app = "@alfresco-proxy"
container_name = "alfresco-proxy"
image_name = "hmpps/spgw-alfresco-proxy"