version: 0.2

env:
  variables:
    APPLICATION_NAME: 'SPG Alfresco Proxy'
    SPG_ALFRESCO_HEALTH_ENDPOINT: '/afresco/s/admin-spg/healthcheck'
    SPG_ALFRESCO_BASE_URL: ''
    test_results_bucket: 'tf-eu-west-2-hmpps-eng-dev-ci-test-results-s3bucket'
    project_name: 'hmpps-po-alfresco-proxy'
    PROJECT_NAME: 'hmpps-alfresco-proxy'
    TZ: 'Europe/London'
phases:
  install:
    runtime-versions:
      docker: 19
      java: corretto8
    commands:
      - ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime
      - echo ${TZ} > /etc/timezone
      - apt-get update
      - apt-get install jq -y
  pre_build:
    commands:
      - ${CODEBUILD_SRC_DIR}/scripts/image-tag-postfix.sh
  build:
    commands:
      - ./gradlew clean test cucumber
  post_build:
    commands:
      - ${CODEBUILD_SRC_DIR}/scripts/archive-application-test-artifacts.sh
reports:
  UnitTestReports:
    files:
      - '**/*'
    base-directory: 'build/test-results'
    file-format: 'JunitXml'
  IntegrationTestReports:
    files:
      - 'cucumber.json'
    base-directory: 'build/cucumber'
    file-format: 'CucumberJson'
artifacts:
  files:
    - '**/*'
  name: $Env:PROJECT_NAME-$(date +%Y-%m-%d-%H-%m-%S)